all: crea_fichero insertarx append invirtiendo_fichero insertarx2

crea_fichero: crea_fichero.c
	gcc -o crea_fichero crea_fichero.c
	
insertarx: insertarx.c
	gcc -o insertarx insertarx.c
	
append: append.c
	gcc -o append append.c	
		
invirtiendo_fichero: invirtiendo_fichero.c
	gcc -o invirtiendo_fichero invirtiendo_fichero.c
	
insertarx2: insertarx2.c
	gcc -o insertarx2 insertarx2.c

clean: 
	rm -f crea_fichero insertarx append invirtiendo_fichero insertarx2
